"""
Delivery Man Database Model
===========================
SQLAlchemy ORM model for the 'delivery_men' table.

PURPOSE:
Represents a Delivery Man user in the system. Delivery Men are field staff
who deliver orders to shops and collect payments/recoveries.

HIERARCHY:
Distributor → Delivery Man → Deliveries (marks) → Daily Collections (submits)

RESPONSIBILITIES:
- Deliver orders to shops (mark as delivered/failed)
- Collect payments from shops
- Submit daily collection reports
- Upload proof photos for failed deliveries

RELATIONSHIPS:
- Belongs to a Distributor (via distributor_id foreign key)
- Belongs to a Zone (via zone_id foreign key)
- Assigned to Orders (via orders.delivery_man_id)
- Creates Deliveries (via deliveries.delivery_man_id)
- Submits Daily Collections (via daily_collections.collected_by_delivery_man)

AUTHENTICATION:
- Uses phone number + password for login
- Password is stored as bcrypt hash
- JWT token is issued on successful login

DATABASE TABLE: delivery_men
"""
from sqlalchemy import Column, BigInteger, String, DateTime, ForeignKey, Boolean
from sqlalchemy.sql import func
from config.database import Base


class DeliveryMan(Base):
    """
    Delivery Man table model.
    
    Maps to the 'delivery_men' table in PostgreSQL.
    Each delivery man is assigned to a distributor and works in a specific zone.
    """
    __tablename__ = "delivery_men"

    # Primary Key
    id = Column(BigInteger, primary_key=True, index=True)
    """
    Primary key: Unique identifier for the delivery man.
    Auto-incremented by database.
    Used as foreign key in: orders, deliveries, daily_collections
    """

    # Relationships
    distributor_id = Column(BigInteger, ForeignKey("distributors.id"), nullable=False)
    """
    Foreign key to distributors table.
    - Required: Every delivery man must belong to a distributor
    - Links delivery man to their managing distributor
    - Used for filtering delivery men by distributor
    - Cascade: If distributor is deleted, delivery men may be affected
    """

    zone_id = Column(BigInteger, ForeignKey("zones.id"), nullable=True)
    """
    Foreign key to zones table.
    - Links delivery man to their assigned geographic zone
    - Nullable: Can be assigned later
    - Used for filtering delivery men by zone
    - Ensures delivery man only works in assigned zone
    """

    # Basic Information
    name = Column(String, nullable=False)
    """
    Delivery Man's full name.
    Required field, used for display and identification.
    Example: "Hassan Ali", "Fatima Khan"
    """

    phone = Column(String, nullable=False, unique=True, index=True)
    """
    Delivery Man's phone number.
    - Required field (used for login)
    - Unique constraint: No two delivery men can have the same phone
    - Indexed for fast lookups during login
    - Format: Usually 11 digits (e.g., "03001234567")
    Note: Delivery men typically don't have email addresses
    """

    # Authentication
    password_hash = Column(String, nullable=False)
    """
    Hashed password using bcrypt.
    - Never stores plain text password
    - Hash includes salt (12 rounds)
    - Generated by AuthService.get_password_hash()
    - Verified by AuthService.verify_password()
    - Format: bcrypt hash string (e.g., "$2b$12$...")
    """

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    """
    Timestamp when delivery man record was created.
    - Automatically set by database on INSERT
    - Timezone-aware (stores UTC)
    - Used for auditing and sorting
    """

    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    """
    Timestamp when delivery man record was last updated.
    - Automatically updated by database on UPDATE
    - Timezone-aware (stores UTC)
    - Used for tracking modifications
    - Null on initial creation
    """

    # Soft Delete
    deleted_at = Column(DateTime(timezone=False), nullable=True)
    """
    Soft delete timestamp.
    - When set, delivery man is considered deleted but data is preserved for audit
    - NULL = active record
    - Used for soft delete functionality
    """

    # Activation Status
    is_active = Column(Boolean, nullable=False, default=True)
    """
    Activation status.
    - TRUE = active (can login and work)
    - FALSE = inactive (blocked from system)
    - Default: TRUE
    - Used for temporary suspension without deletion
    """

