"""
Distributor Database Model
==========================
SQLAlchemy ORM model for the 'distributors' table.

PURPOSE:
Represents a Distributor user in the system. Distributors are regional managers
who can create and manage Order Bookers, Delivery Men, and Zones.

HIERARCHY:
Super Admin → Distributor → Order Booker / Delivery Man

RELATIONSHIPS:
- Has many Order Bookers (via order_bookers.distributor_id)
- Has many Delivery Men (via delivery_men.distributor_id)
- Can create Zones (via zones - distributors create zones but are not assigned to them)
- Can create Routes (via routes.created_by_distributor)

IMPORTANT:
- Distributors are NOT assigned to zones - they can create and manage zones
- Order Bookers and Delivery Men are assigned to zones
- Distributors oversee operations across all zones they create

AUTHENTICATION:
- Uses phone number + password for login
- Password is stored as bcrypt hash (never plain text)
- JWT token is issued on successful login

DATABASE TABLE: distributors
"""
from sqlalchemy import Column, BigInteger, String, DateTime, ForeignKey
from sqlalchemy.sql import func
from config.database import Base


class Distributor(Base):
    """
    Distributor table model.
    
    Maps to the 'distributors' table in PostgreSQL.
    Each distributor represents a regional manager who can create and manage
    zones, order bookers, delivery men, and routes.
    """
    __tablename__ = "distributors"

    # Primary Key
    id = Column(BigInteger, primary_key=True, index=True)
    """
    Primary key: Unique identifier for the distributor.
    Auto-incremented by database.
    Used as foreign key in: order_bookers, delivery_men, routes
    """

    # Basic Information
    name = Column(String, nullable=False)
    """
    Distributor's full name.
    Required field, used for display and identification.
    Example: "John Doe", "Faraz Ahmed"
    """

    email = Column(String, unique=True, index=True)
    """
    Distributor's email address.
    - Unique constraint: No two distributors can have the same email
    - Indexed for fast lookups during login/registration
    - Optional (nullable), but recommended for communication
    Example: "john@tuliptea.com"
    """

    phone = Column(String, nullable=False, unique=True, index=True)
    """
    Distributor's phone number.
    - Required field (used for login)
    - Unique constraint: No two distributors can have the same phone
    - Indexed for fast lookups during login
    - Format: Usually 11 digits (e.g., "03001234567")
    """

    # Authentication
    password_hash = Column(String, nullable=False)
    """
    Hashed password using bcrypt.
    - Never stores plain text password
    - Hash includes salt (12 rounds)
    - Generated by AuthService.get_password_hash()
    - Verified by AuthService.verify_password()
    - Format: bcrypt hash string (e.g., "$2b$12$...")
    """

    # Relationships
    # Note: Distributors are NOT assigned to zones
    # They can create zones, but zones are assigned to Order Bookers and Delivery Men
    # This allows distributors to manage multiple zones

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    """
    Timestamp when distributor record was created.
    - Automatically set by database on INSERT
    - Timezone-aware (stores UTC)
    - Used for auditing and sorting
    """

    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    """
    Timestamp when distributor record was last updated.
    - Automatically updated by database on UPDATE
    - Timezone-aware (stores UTC)
    - Used for tracking modifications
    - Null on initial creation
    """

