"""
Order Booker Database Model
============================
SQLAlchemy ORM model for the 'order_bookers' table.

PURPOSE:
Represents an Order Booker user in the system. Order Bookers are field staff
who visit shops, register new shops, and create orders for delivery.

HIERARCHY:
Distributor → Order Booker → Shops (registers) → Orders (creates)

RESPONSIBILITIES:
- Register new shops (with GPS coordinates)
- Create orders for shops
- Visit shops on assigned routes
- Collect payments/recoveries

RELATIONSHIPS:
- Belongs to a Distributor (via distributor_id foreign key)
- Belongs to a Zone (via zone_id foreign key)
- Can have Routes assigned (via routes.order_booker_id)
- Creates Shops (via shops.created_by_order_booker)
- Creates Orders (via orders.order_booker_id)

AUTHENTICATION:
- Uses phone number + password for login
- Password is stored as bcrypt hash
- JWT token is issued on successful login

DATABASE TABLE: order_bookers
"""
from sqlalchemy import Column, BigInteger, String, DateTime, ForeignKey
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from config.database import Base


class OrderBooker(Base):
    """
    Order Booker table model.
    
    Maps to the 'order_bookers' table in PostgreSQL.
    Each order booker is assigned to a distributor and works in a specific zone.
    """
    __tablename__ = "order_bookers"

    # Primary Key
    id = Column(BigInteger, primary_key=True, index=True)
    """
    Primary key: Unique identifier for the order booker.
    Auto-incremented by database.
    Used as foreign key in: shops, routes, orders
    """

    # Relationships
    distributor_id = Column(BigInteger, ForeignKey("distributors.id"), nullable=False)
    """
    Foreign key to distributors table.
    - Required: Every order booker must belong to a distributor
    - Links order booker to their managing distributor
    - Used for filtering order bookers by distributor
    - Cascade: If distributor is deleted, order bookers may be affected
    """

    zone_id = Column(BigInteger, ForeignKey("zones.id"), nullable=True)
    """
    Foreign key to zones table.
    - Links order booker to their assigned geographic zone
    - Nullable: Can be assigned later
    - Used for filtering order bookers by zone
    - Ensures order booker only works in assigned zone
    """

    # Basic Information
    name = Column(String, nullable=False)
    """
    Order Booker's full name.
    Required field, used for display and identification.
    Example: "Ahmed Khan", "Sara Ali"
    """

    email = Column(String, unique=True, index=True, nullable=True)
    """
    Order Booker's email address.
    - Unique constraint: No two order bookers can have the same email
    - Indexed for fast lookups
    - Optional (nullable), but recommended for communication
    Example: "ahmed@tuliptea.com"
    """

    phone = Column(String, nullable=False, unique=True, index=True)
    """
    Order Booker's phone number.
    - Required field (used for login)
    - Unique constraint: No two order bookers can have the same phone
    - Indexed for fast lookups during login
    - Format: Usually 11 digits (e.g., "03001234567")
    """

    # Authentication
    password_hash = Column(String, nullable=False)
    """
    Hashed password using bcrypt.
    - Never stores plain text password
    - Hash includes salt (12 rounds)
    - Generated by AuthService.get_password_hash()
    - Verified by AuthService.verify_password()
    - Format: bcrypt hash string (e.g., "$2b$12$...")
    """

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    """
    Timestamp when order booker record was created.
    - Automatically set by database on INSERT
    - Timezone-aware (stores UTC)
    - Used for auditing and sorting
    """

    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    """
    Timestamp when order booker record was last updated.
    - Automatically updated by database on UPDATE
    - Timezone-aware (stores UTC)
    - Used for tracking modifications
    - Null on initial creation
    """

