"""
Super Admin Database Model
==========================
SQLAlchemy ORM model for the 'super_admins' table.

PURPOSE:
Represents a Super Admin user who has full system access and can manage
all entities (distributors, order bookers, delivery men, shops, zones, routes)
including activation/deactivation.

HIERARCHY:
Super Admin → Distributor → Order Booker / Delivery Man

AUTHENTICATION:
- Uses email + password for login
- Password is stored as bcrypt hash (never plain text)
- JWT token is issued on successful login

DATABASE TABLE: super_admins
"""
from sqlalchemy import Column, BigInteger, String, DateTime, Boolean
from sqlalchemy.sql import func
from config.database import Base


class SuperAdmin(Base):
    """
    Super Admin table model.
    
    Maps to the 'super_admins' table in PostgreSQL.
    Super admins have full system access and can manage all entities.
    """
    __tablename__ = "super_admins"

    # Primary Key
    id = Column(BigInteger, primary_key=True, index=True)
    """
    Primary key: Unique identifier for the super admin.
    Auto-incremented by database.
    """

    # Basic Information
    name = Column(String, nullable=False)
    """
    Super Admin's full name.
    Required field, used for display and identification.
    Example: "System Administrator"
    """

    email = Column(String, unique=True, index=True, nullable=False)
    """
    Super Admin's email address.
    - Unique constraint: No two super admins can have the same email
    - Indexed for fast lookups during login
    - Required field (used for login)
    Example: "admin@tuliptea.com"
    """

    phone = Column(String, nullable=True, unique=True, index=True)
    """
    Super Admin's phone number (optional).
    - Optional field
    - Unique constraint if provided
    - Indexed for fast lookups
    - Format: Usually 11 digits (e.g., "03001234567")
    """

    # Authentication
    password_hash = Column(String, nullable=False)
    """
    Hashed password using bcrypt.
    - Never stores plain text password
    - Hash includes salt (12 rounds)
    - Generated by AuthService.get_password_hash()
    - Verified by AuthService.verify_password()
    - Format: bcrypt hash string (e.g., "$2b$12$...")
    """

    # Activation Status
    is_active = Column(Boolean, nullable=False, default=True)
    """
    Activation status.
    - TRUE = active (can login and use system)
    - FALSE = inactive (blocked from system)
    - Default: TRUE
    """

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    """
    Timestamp when super admin record was created.
    - Automatically set by database on INSERT
    - Timezone-aware (stores UTC)
    - Used for auditing and sorting
    """

    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    """
    Timestamp when super admin record was last updated.
    - Automatically updated by database on UPDATE
    - Timezone-aware (stores UTC)
    - Used for tracking modifications
    - Null on initial creation
    """





